#! /bin/bash

sudo echo "_JAVA_AWT_WM_NONREPARENTING=1" > /etc/environment

sleep 1

echo "Installing Arch User Repository Helper"

git clone https://aur.archlinux.org/paru.git && cd paru

makepkg -si

sleep 1

echo "Installing needed packages"

paru -Syu feh git firefox steam discord rofi polybar zsh maim ntfs-3g gvfs thunar thunar-volman thunar-archive-plugin file-roller dunst xorg-xsetroot polkit

sleep 1

echo "Installed needed packages"