#! /bin/sh

bspc monitor -d '' '' '' '' '' '' '' '調' ''

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a xfce4-terminal desktop='^1' follow=on focus=on

# 2 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done
bspc rule -a "Emacs" desktop='^2' state=fullscreen follow=on focus=on

# 3 > web
bspc rule -a firefox desktop='^3' follow=on focus=on

# 4 > files
declare -a files=(Pcmanfm Thunar qBittorren)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done
bspc rule -a 'DBeaver' desktop='^4' follow=on focus=on

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
declare -a comm=(Thunderbird TelegramDesktop Hexchat discord)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

# 7 > media
declare -a media=(Audacity mpv Music MPlayer Lxmusic Inkscape Gimp-2.10 obs viewnior Minecraft)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=fullscreen follow=on focus=on; done
bspc rule -a 'zoom' desktop='^7' state=floating follow=off focus=on

# 8 > Game
declare -a games=(Terraria Brawlhalla)
bspc rule -a 'Steam' desktop='^8' state=floating follow=off 
for i in ${games[@]}; do
  bspc rule -a $i desktop='^8' state=fullscreen follow=on; done
bspc rule -a 'Lutris' desktop='^8' state=floating follow=on

# 8 > settings
bspc rule -a 'Nitrogen' desktop='^9' follow=on focus=on
bspc rule -a 'VirtualBox Manager' desktop='^9' follow=on focus=on state=fullscreen
bspc rule -a 'Virtualbox Machine' desktop '^9' follow=on focus=on state=fullscreen
bspc rule -a 'vmplayer' desktop='^9' follow=on focus=on
bspc rule -a GParted desktop='^9' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^9' state=floating follow=on focus=on; done

# Border
bspc config focused_border_color        "#AA336A"
bspc config normal_border_color         "#6c71c4"
bspc config active_border_color         "#6c71c4"

#Kill if running
killall -9 xsettingsd sxhkd dunst ksuperkey picom

#
# Autostart
#

# Bar
~/.config/polybar/launch.sh &

#Notifications
dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
#nitrogen --restore &
feh --bg-fill /usr/share/backgrounds/main.png

# Picom
picom --experimental-backends &

# Keyboard
sxhkd &

# Cursor
xsetroot -cursor_name left_ptr &

#Emacs Daemon
/usr/bin/emacs --daemon &

